openapi: 3.0.0
info:
  version: 1.0.0
  title: Selin microservices environment manager
  license:
    name: LGPL
servers:
  - url: https://selin.ithings.ch/v1
paths:
  /environments:
    get:
      summary: List all environments
      operationId: listEnvironments
      tags:
        - environments
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
            format: int32
      responses:
        200:
          description: An paged array of environments
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Environments"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      summary: Create an environment
      operationId: createEnvironment
      tags:
        - environments
      requestBody:
        content:
          "application/json":
            schema:
              $ref: "#/components/schemas/Environment"
      responses:
        201:
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /environments/{environmentId}:
    get:
      summary: Info for a specific environment
      operationId: getEnvironmentById
      security:
        - api_key: []
      tags:
        - environments
      parameters:
        - name: environmentId
          in: path
          required: true
          description: The id of the environment to retrieve
          schema:
            type: string
      responses:
        200:
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Environment"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Environment:
      type: object
      required:
        - name
        - creator
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        creator:
          type: string
        tag:
          type: string
    Environments:
      type: array
      items:
        $ref: "#/components/schemas/Environment"
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
  securitySchemes:
    api_key:
      type: apiKey
      name: api_key
      in: header
      openIdConnectUrl: "https://auth.ithings.ch" # I don't know why but this parameter is required even if type is basic or apiKey. I think It's OAS bug